import type { EditorConfig } from '@ckeditor/ckeditor5-core/src/editor/editorconfig';

type CustomEditConfig = EditorConfig;

declare global {
	interface Window {
		editor: ClassicEditor;
	}
}

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import CKEditorInspector from '@ckeditor/ckeditor5-inspector';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import CodeBlock from '@ckeditor/ckeditor5-code-block/src/codeblock';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code';

import { MyPlugin, Ywbox } from '../src';
import ImageUploadPlugin from '../src/image/upload/ImageUploadPlugin';

ClassicEditor
	.create( document.getElementById( 'editor' )!, {
		extraPlugins: [ ImageUploadPlugin, Ywbox ],
		plugins: [
			Essentials,
			Autoformat,
			BlockQuote,
			Bold,
			Heading,
			Image,
			ImageCaption,
			ImageStyle,
			ImageToolbar,
			ImageUpload,
			Indent,
			Italic,
			Link,
			List,
			MediaEmbed,
			Paragraph,
			Table,
			TableToolbar,
			CodeBlock,
			Code,
			// `MyPlugin` is an example plugin generated by the package generator.
			MyPlugin
		],
		toolbar: [
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'code',
			'bulletedList',
			'numberedList',
			'|',
			'outdent',
			'indent',
			'|',
			'uploadImage',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'codeBlock',
			'|',
			'undo',
			'redo',
			'|',
			// `myButton` is an example button provided by the `MyPlugin` class.
			'myButton',
			'ywbox'
		],
		image: {
			toolbar: [
				'imageStyle:inline',
				'imageStyle:block',
				'imageStyle:side',
				'|',
				'imageTextAlternative'
			]
		},
		table: {
			contentToolbar: [
				'tableColumn',
				'tableRow',
				'mergeTableCells'
			]
		},
		ywImageUpload: { // ImageUploadPlugin
			handle: ( loader: any, options: any, file: any, resolve: any, reject: any ) => {
				const uploaded = true;
				if ( uploaded ) {
					resolve( {
						urls: {
							default: 'https://www.youdeyiwu.com/_next/image?url=' +
								'https%3A%2F%2Fwww.youdeyiwu.com%2Foss%2Fyoudeyiwu%2Fforum%2Fsection%2Fcover%2F1%2F220924%2F' +
								'9IOjU2z5YwHn&w=384&q=75'
						}
					} );
				} else {
					reject( 'custom image upload failure' );
				}
			}
			// controller: new AbortController()
		},
		ywBox: {
			onOpen: ( { onSelect }: { onSelect: ( file: object ) => void } ) => {
				// onSelect( {
				// 	id: '123456',
				// 	originalName: 'test.png'
				// } );

				onSelect( {
					id: '123456',
					originalName: 'test.png',
					isImage: true,
					urls: {
						default: 'https://www.youdeyiwu.com/_next/image?url=' +
							'https%3A%2F%2Fwww.youdeyiwu.com%2Foss%2Fyoudeyiwu%2Fforum%2Fsection%2Fcover%2F1%2F220924%2F' +
							'9IOjU2z5YwHn&w=384&q=75'
					}
				} );
			}
		}
	} as CustomEditConfig )
	.then( editor => {
		window.editor = editor;
		CKEditorInspector.attach( editor );
		window.console.log( 'CKEditor 5 is ready.', editor );
	} )
	.catch( err => {
		window.console.error( err.stack );
	} );
